import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Loader2, FileText, LogOut } from "lucide-react";
import { useAuthStore, apiRequest, logout } from "@/lib/auth";

export function TermsAcceptanceModal() {
  const { user, updateUser } = useAuthStore();
  const [isAccepting, setIsAccepting] = useState(false);
  const [agreed, setAgreed] = useState(false);
  const [error, setError] = useState("");

  const needsToAcceptTerms = user && !user.termsAcceptedAt;

  const handleAccept = async () => {
    if (!agreed) {
      setError("You must agree to the terms to continue");
      return;
    }

    setIsAccepting(true);
    setError("");

    try {
      const response = await apiRequest("/api/auth/accept-terms", {
        method: "POST",
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Failed to accept terms");
      }

      const data = await response.json();
      updateUser({ termsAcceptedAt: data.termsAcceptedAt });
    } catch (err: any) {
      setError(err.message || "An error occurred");
    } finally {
      setIsAccepting(false);
    }
  };

  const handleLogout = async () => {
    await logout();
    window.location.href = "/login";
  };

  if (!needsToAcceptTerms) {
    return null;
  }

  return (
    <Dialog open={true}>
      <DialogContent className="max-w-3xl max-h-[90vh] [&>button]:hidden">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl">
            <FileText className="h-5 w-5 text-primary" />
            User Agreement Required
          </DialogTitle>
          <DialogDescription>
            Please review and accept our User Agreement to continue using BidForge AI.
          </DialogDescription>
        </DialogHeader>

        <ScrollArea className="h-[50vh] pr-4 border rounded-lg bg-slate-50 p-4">
          <div className="prose prose-sm max-w-none text-slate-700 space-y-4">
            <p className="text-amber-700 bg-amber-50 p-3 rounded-lg border border-amber-200 text-xs">
              <strong>Disclaimer:</strong> This document is a draft for educational and planning purposes. It does not constitute legal advice. You must have this reviewed by a qualified attorney in your jurisdiction.
            </p>

            <div className="text-center border-b pb-4 mb-4">
              <h2 className="text-lg font-bold text-slate-800 m-0">DRAFT USER AGREEMENT (TERMS OF SERVICE)</h2>
              <p className="text-sm text-slate-500 m-0">Platform: BidForgeAI.com</p>
              <p className="text-sm text-slate-500 m-0">Last Updated: December 22, 2025</p>
            </div>

            <section>
              <h3 className="text-base font-semibold text-slate-800">1. Introduction and Acceptance</h3>
              <p>This User Agreement ("Agreement") is a binding legal contract between you ("User," "You," or "Customer") and <strong>BidForgeAI</strong> ("Company," "We," "Us," or "Our"). By registering for, accessing, or using the services provided at <strong>bidforgeai.com</strong> (the "Service"), you agree to be bound by these terms.</p>
              <p className="font-semibold">IF YOU DO NOT AGREE TO ALL OF THESE TERMS, DO NOT USE THE SERVICE.</p>
            </section>

            <section>
              <h3 className="text-base font-semibold text-slate-800">2. The Nature of AI Services</h3>
              <p>You acknowledge that the Service utilizes Generative Artificial Intelligence ("AI") technologies, including Large Language Models (LLMs), to assist in drafting, analyzing, and summarizing Request for Proposal (RFP) and Request for Quotation (RFQ) responses.</p>
              
              <h4 className="text-sm font-semibold text-slate-700 mt-3">2.1 No Guarantee of Accuracy (The "Hallucination" Clause)</h4>
              <p><strong>IMPORTANT:</strong> AI technologies are probabilistic and experimental. They may produce "hallucinations"—content that sounds plausible but is factually incorrect, nonsensical, or unrelated to your input.</p>
              <ul className="list-disc pl-5 space-y-1">
                <li><strong>We do not guarantee</strong> that the AI-generated content is accurate, complete, valid, or compliant with specific RFP requirements.</li>
                <li><strong>We do not guarantee</strong> that the calculations, pricing models, or technical specifications generated by the AI are mathematically or technically correct.</li>
              </ul>
            </section>

            <section>
              <h3 className="text-base font-semibold text-slate-800">3. Mandatory Human Verification ("Human-in-the-Loop")</h3>
              <p><strong>You agree that you are solely responsible for reviewing, verifying, and validating all output generated by BidForgeAI.</strong></p>
              
              <h4 className="text-sm font-semibold text-slate-700 mt-3">3.1 Your Obligation to Verify</h4>
              <p>Before submitting, sharing, or relying on any content generated by the Service, you must:</p>
              <ol className="list-decimal pl-5 space-y-1">
                <li><strong>Verify Facts:</strong> Cross-reference all technical data, dates, and compliance claims against the original RFP documents.</li>
                <li><strong>Check Pricing:</strong> Manually validate all financial figures, currency conversions, and cost estimates.</li>
                <li><strong>Review Legal Terms:</strong> Ensure that any generated legal language complies with your internal policies and the laws of the jurisdiction in which you are bidding.</li>
              </ol>

              <h4 className="text-sm font-semibold text-slate-700 mt-3">3.2 Waiver of Reliance</h4>
              <p>You expressly agree that you will not rely solely on the Service for critical decision-making. You acknowledge that <strong>BidForgeAI is a drafting aid, not a substitute for professional human judgment</strong>, engineering review, or legal counsel.</p>
            </section>

            <section>
              <h3 className="text-base font-semibold text-slate-800">4. User Liability for Submissions</h3>
              <p><strong>You assume full liability for any RFP, RFQ, or tender response you submit that utilizes content from BidForgeAI.</strong></p>
              <ul className="list-disc pl-5 space-y-1">
                <li><strong>Submission Errors:</strong> If you submit a bid containing errors (e.g., incorrect pricing, missing certifications, false technical claims) caused by AI generation, <strong>you bear the sole consequences</strong>, including but not limited to bid disqualification, contractual penalties, financial loss, or reputational damage.</li>
                <li><strong>No Vicarious Liability:</strong> BidForgeAI shall not be considered a partner, joint venturer, or co-author of your bids. We are a software provider only.</li>
              </ul>
            </section>

            <section>
              <h3 className="text-base font-semibold text-slate-800">5. Intellectual Property</h3>
              <h4 className="text-sm font-semibold text-slate-700 mt-3">5.1 Your Data</h4>
              <p>You retain ownership of the data and documents you upload to the Service ("User Input"). You grant us a limited, non-exclusive license to process this data solely to provide the Service to you.</p>
              
              <h4 className="text-sm font-semibold text-slate-700 mt-3">5.2 AI Output</h4>
              <p>Subject to your compliance with this Agreement, BidForgeAI assigns to you all right, title, and interest in the final output generated by the Service for your specific inputs.</p>
            </section>

            <section>
              <h3 className="text-base font-semibold text-slate-800">6. Limitation of Liability (The "Shield")</h3>
              <p className="font-semibold">TO THE FULLEST EXTENT PERMITTED BY LAW, BIDFORGEAI SHALL NOT BE LIABLE FOR:</p>
              <ol className="list-decimal pl-5 space-y-1">
                <li><strong>Lost Bids or Revenue:</strong> Any loss of business, loss of contract, failure to win a tender, or loss of anticipated savings arising from your use of the Service.</li>
                <li><strong>Inaccurate Content:</strong> Damages resulting from errors, omissions, or inaccuracies in the AI-generated content.</li>
                <li><strong>Indirect Damages:</strong> Any indirect, incidental, special, consequential, or punitive damages.</li>
              </ol>
              <p className="mt-2"><strong>CAP ON LIABILITY:</strong> IN NO EVENT SHALL BIDFORGEAI'S TOTAL AGGREGATE LIABILITY EXCEED THE AMOUNT ACTUALLY PAID BY YOU TO BIDFORGEAI FOR THE SERVICE IN THE <strong>SIX (6) MONTHS</strong> PRECEDING THE CLAIM.</p>
            </section>

            <section>
              <h3 className="text-base font-semibold text-slate-800">7. Indemnification</h3>
              <p>You agree to defend, indemnify, and hold harmless BidForgeAI, its officers, directors, and employees from and against any claims, liabilities, damages, losses, and expenses (including legal fees) arising out of or in any way connected with:</p>
              <ul className="list-disc pl-5 space-y-1">
                <li><strong>Your use of the Service.</strong></li>
                <li><strong>Any RFP/RFQ response you submit</strong> (including claims by third parties regarding false advertising, breach of contract, or negligence).</li>
                <li><strong>Your violation of any third-party rights</strong> (including intellectual property or confidentiality obligations contained in the RFPs you upload).</li>
              </ul>
            </section>

            <section>
              <h3 className="text-base font-semibold text-slate-800">8. Data Security and Confidentiality</h3>
              <p>While we employ industry-standard security measures, you acknowledge that no AI processing pipeline is 100% secure. You agree not to upload highly sensitive information (such as state secrets, classified government data, or unredacted PII) unless explicitly covered by a separate Enterprise Agreement.</p>
            </section>

            <section>
              <h3 className="text-base font-semibold text-slate-800">9. Governing Law and Dispute Resolution</h3>
              <p>This Agreement shall be governed by the laws of the applicable jurisdiction. Any dispute arising from this Agreement shall be resolved through binding arbitration, except that either party may seek injunctive relief in court.</p>
            </section>
          </div>
        </ScrollArea>

        {error && (
          <p className="text-red-500 text-sm">{error}</p>
        )}

        <div className="flex items-start space-x-3 pt-2">
          <Checkbox
            id="accept-terms"
            checked={agreed}
            onCheckedChange={(checked) => setAgreed(checked as boolean)}
            className="mt-1 border-slate-400 data-[state=checked]:bg-primary data-[state=checked]:border-primary"
            data-testid="checkbox-accept-terms"
          />
          <label htmlFor="accept-terms" className="text-sm text-slate-600 leading-relaxed cursor-pointer">
            I have read, understand, and agree to the User Agreement. I acknowledge that AI-generated content requires human verification before use.
          </label>
        </div>

        <div className="flex gap-3 justify-end pt-2">
          <Button
            variant="outline"
            onClick={handleLogout}
            className="gap-2"
            data-testid="button-logout-terms"
          >
            <LogOut className="h-4 w-4" />
            Log Out
          </Button>
          <Button
            onClick={handleAccept}
            disabled={!agreed || isAccepting}
            className="gap-2"
            data-testid="button-accept-terms"
          >
            {isAccepting && <Loader2 className="h-4 w-4 animate-spin" />}
            Accept & Continue
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
